name: Unit Tests

on:
  workflow_dispatch:
    branches:
      - main
      - development
    inputs:
      coverage:
        description: 'Generate coverage report'
        required: false
        type: boolean
        default: false
  workflow_call:
    inputs:
      coverage:
        description: 'Generate coverage report'
        required: false
        type: boolean
        default: false
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        if: ${{ !inputs.coverage }}
        run: npm test

      - name: Run tests with coverage
        if: ${{ inputs.coverage }}
        run: npm test -- --coverage

      - name: Upload coverage reports as artifact
        if: ${{ inputs.coverage }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
          retention-days: 7

      - name: Deploy coverage to GitHub Pages
        if: ${{ inputs.coverage && github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage
          destination_dir: coverage

      - name: Comment coverage URL on workflow
        if: ${{ inputs.coverage }}
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
          echo "::notice::Coverage report will be available at: https://${{ github.repository_owner }}.github.io/${REPO_NAME}/coverage/"

      - name: Display test results
        if: always()
        run: echo "Tests completed successfully"